### ISSUE TITLE
The Wire.available() is always smaller or equal to the number of requested bytes.

### ISSUE THREAD

**Issue by Koepel** [UFPelRocketTeam/NAVSYS#3]
In the file "gy85.ino" a number of times this code is used:
```
Wire.requestFrom(ACCEL, 2);
if (Wire.available() <= 2){
  ...
```
However, the Wire.available() always returns a value that is lower or equal than the number of bytes that was requested. When there was a problem, the Wire.available() might return a value of zero.

This is checking the number of received bytes:
```
Wire.requestFrom(ACCEL, 2);
if (Wire.available() == 2){
	ACCx = Wire.read() ;
	ACCx |= Wire.read()<< 8;
}
```

Since the returned error code of Wire.endTransmission() is not checked, the check for the number of received bytes could be omitted as well. Therefor you would have the same functionality of the code if you change it to this:
```
Wire.requestFrom(ACCEL, 2);
ACCx = Wire.read() ;
ACCx |= Wire.read()<< 8;
```

**Comment by enjoycowboy** [comment]
Thanks for the input! We don't intend on checking for errors on the Wire.endTransmission method during broadcast since it would be too heavy of a penalty to have a miss on writing the buffer to be broadcast, and it shouldn't happen anyway if we are reading everything correctly.

**Comment by Koepel** [comment]
I agree: [Check for bus errors ?](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Check-for-bus-errors-%3F)
This issue was about the `if (Wire.available() <= 2){`, which does not do anything because it is always true. Do you still plan to remove it ?
